In [2]:
import torch

In [3]:
!nvidia-smi

Fri Jul 22 12:39:44 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.57       Driver Version: 515.57       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    Off  | 00000000:41:00.0 Off |                  Off |
| 33%   62C    P2    94W / 300W |   1819MiB / 49140MiB |     17%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [101]:
a = torch.arange(1, 11).reshape((5, -1))

print(type(a.size()))

<class 'torch.Size'>


In [111]:
a = torch.arange(1, 11).reshape((2, -1))
b = torch.arange(1, 13).reshape((3, -1))
c = torch.arange(1, 100 + 1).reshape((5, -1))

tensor = c
print(f"Dimension : {tensor.size()}")
for i in range(tensor.size(0)):
    print(f"Tensor[{i}] : ", end='')

    for j in range(tensor.size(1)):
        print(f"{tensor[i][j]}  ", end='')

    print()


Dimension : torch.Size([5, 20])
Tensor[0] : 1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  
Tensor[1] : 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  
Tensor[2] : 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  
Tensor[3] : 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  
Tensor[4] : 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99  100  


In [141]:
d = torch.arange(1, 25).reshape((3, 2, -1))
e = torch.arange(1, 101).reshape((10, 2, -1))

tensor = e
print(f"Dimension :{tensor.size()}")
for i in range(tensor.size(0)):
    print(f"image : {i}")

    for j in range(tensor.size(1)):
        print(f"Tensor[{i}][{j}] : ", end='')

        for k in range(tensor.size(2)):
            print(f"{tensor[i][j][k]} ", end='')
            # print(tensor[i][j][k].item(),", ", end='')
        print()

Dimension :torch.Size([10, 2, 5])
image : 0
Tensor[0][0] : 1 2 3 4 5 
Tensor[0][1] : 6 7 8 9 10 
image : 1
Tensor[1][0] : 11 12 13 14 15 
Tensor[1][1] : 16 17 18 19 20 
image : 2
Tensor[2][0] : 21 22 23 24 25 
Tensor[2][1] : 26 27 28 29 30 
image : 3
Tensor[3][0] : 31 32 33 34 35 
Tensor[3][1] : 36 37 38 39 40 
image : 4
Tensor[4][0] : 41 42 43 44 45 
Tensor[4][1] : 46 47 48 49 50 
image : 5
Tensor[5][0] : 51 52 53 54 55 
Tensor[5][1] : 56 57 58 59 60 
image : 6
Tensor[6][0] : 61 62 63 64 65 
Tensor[6][1] : 66 67 68 69 70 
image : 7
Tensor[7][0] : 71 72 73 74 75 
Tensor[7][1] : 76 77 78 79 80 
image : 8
Tensor[8][0] : 81 82 83 84 85 
Tensor[8][1] : 86 87 88 89 90 
image : 9
Tensor[9][0] : 91 92 93 94 95 
Tensor[9][1] : 96 97 98 99 100 


In [143]:
#tensor([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10]])
src = torch.arange(1, 11).reshape((2, 5))
print(src,"\n")

#tensor([[0, 1, 2, 0]])
index = torch.tensor([[0, 1, 2, 0]])
print(index, "\n")


torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]) 

tensor([[0, 1, 2, 0]]) 



tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [32]:
# torch.Tensor.scatter_(dim, index, src, reduce)
torch.full((2, 4), 2).scatter_(1, torch.tensor([[2], [3]]), 1.23, reduce='multiply')


tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]])

In [ ]:
torch.full((2, 4), 2.).scatter_(1, torch.tensor([[2], [3]]), 1.23, reduce='add')